/*
 * HalcyonScript Compiler
 * Main header file
 * Developer: KAInaps
 */

#ifndef HALCYON_H
#define HALCYON_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <ctype.h>
#include <math.h>

#define HALCYON_VERSION "0.9.26"
#define HALCYON_RT_NAME "HalcyonRT"
#define MAX_STRING_LEN 65536
#define MAX_IDENTIFIER_LEN 256
#define MAX_TOKENS 100000
#define MAX_VARIABLES 10000
#define MAX_FUNCTIONS 1000
#define MAX_CONTROLS 1000
#define MAX_EVENTS 1000
#define MAX_TIMERS 100
#define MAX_PARAMS 32
#define MAX_ARRAY_SIZE 100000

/* Token types - prefixed with HCS_ to avoid Windows API conflicts */
typedef enum {
    /* Keywords - UI Controls */
    HCS_TOK_CREATE, HCS_TOK_WINDOW, HCS_TOK_BUTTON, HCS_TOK_LABEL, HCS_TOK_INPUT, HCS_TOK_LISTBOX,
    HCS_TOK_CHECKBOX, HCS_TOK_IMAGE, HCS_TOK_PANEL, HCS_TOK_TEXTAREA, HCS_TOK_DROPDOWN, HCS_TOK_SLIDER,
    HCS_TOK_PROGRESS, HCS_TOK_TAB, HCS_TOK_TABS, HCS_TOK_MENU, HCS_TOK_MENUITEM, HCS_TOK_TOOLBAR,
    HCS_TOK_STATUSBAR, HCS_TOK_TREEVIEW, HCS_TOK_TABLE, HCS_TOK_CANVAS, HCS_TOK_SPLITTER,
    HCS_TOK_SCROLLBAR, HCS_TOK_TOOLTIP, HCS_TOK_DIALOG,
    
    /* Keywords - Events */
    HCS_TOK_WHEN, HCS_TOK_CLICKED, HCS_TOK_CHANGED, HCS_TOK_STARTED, HCS_TOK_CHECKED, HCS_TOK_CLOSED,
    HCS_TOK_RESIZED, HCS_TOK_KEYDOWN, HCS_TOK_KEYUP, HCS_TOK_KEYPRESS, HCS_TOK_MOUSEMOVE,
    HCS_TOK_MOUSEDOWN, HCS_TOK_MOUSEUP, HCS_TOK_DOUBLECLICK, HCS_TOK_RIGHTCLICK, HCS_TOK_FOCUS,
    HCS_TOK_BLUR, HCS_TOK_SCROLL, HCS_TOK_DRAG, HCS_TOK_DROP, HCS_TOK_TIMER, HCS_TOK_TICK,
    HCS_TOK_SELECTED, HCS_TOK_HOVER,
    
    /* Keywords - Actions */
    HCS_TOK_SHOW, HCS_TOK_HIDE, HCS_TOK_CLOSE, HCS_TOK_OPEN, HCS_TOK_MINIMIZE, HCS_TOK_MAXIMIZE,
    HCS_TOK_RESTORE, HCS_TOK_SET, HCS_TOK_GET, HCS_TOK_ADD, HCS_TOK_REMOVE, HCS_TOK_CLEAR, HCS_TOK_INSERT,
    HCS_TOK_UPDATE, HCS_TOK_ENABLE, HCS_TOK_DISABLE, HCS_TOK_FOCUS_ACTION, HCS_TOK_SELECT,
    HCS_TOK_DESELECT, HCS_TOK_PLAY, HCS_TOK_PAUSE, HCS_TOK_STOP, HCS_TOK_RESUME, HCS_TOK_SEEK,
    HCS_TOK_LOAD, HCS_TOK_START, HCS_TOK_INTERVAL, HCS_TOK_TIMEOUT,
    
    /* Keywords - Control flow */
    HCS_TOK_IF, HCS_TOK_ELSE, HCS_TOK_ELSEIF, HCS_TOK_WHILE, HCS_TOK_FOR, HCS_TOK_FROM, HCS_TOK_TO,
    HCS_TOK_STEP, HCS_TOK_BREAK, HCS_TOK_CONTINUE, HCS_TOK_FUNC, HCS_TOK_RETURN, HCS_TOK_IMPORT,
    HCS_TOK_EXPORT, HCS_TOK_CLASS, HCS_TOK_NEW, HCS_TOK_THIS, HCS_TOK_EXTENDS, HCS_TOK_SWITCH,
    HCS_TOK_CASE, HCS_TOK_DEFAULT, HCS_TOK_IN,
    
    /* Keywords - Variables & Types */
    HCS_TOK_VAR, HCS_TOK_CONST, HCS_TOK_LET, HCS_TOK_GLOBAL, HCS_TOK_TRUE, HCS_TOK_FALSE, HCS_TOK_NULL,
    HCS_TOK_AND, HCS_TOK_OR, HCS_TOK_NOT, HCS_TOK_IS, HCS_TOK_AS,
    
    /* Keywords - I/O & Network */
    HCS_TOK_PRINT, HCS_TOK_ALERT, HCS_TOK_CONFIRM, HCS_TOK_PROMPT, HCS_TOK_LOG, HCS_TOK_DEBUG,
    HCS_TOK_READ, HCS_TOK_WRITE, HCS_TOK_APPEND, HCS_TOK_DELETE, HCS_TOK_EXISTS, HCS_TOK_COPY,
    HCS_TOK_MOVE, HCS_TOK_MKDIR, HCS_TOK_LISTDIR, HCS_TOK_HTTP, HCS_TOK_FETCH, HCS_TOK_REQUEST,
    HCS_TOK_RESPONSE, HCS_TOK_WAIT, HCS_TOK_ASYNC, HCS_TOK_AWAIT, HCS_TOK_PARALLEL,
    HCS_TOK_TRY, HCS_TOK_CATCH, HCS_TOK_THROW, HCS_TOK_FINALLY,
    
    /* Keywords - Data */
    HCS_TOK_JSON, HCS_TOK_PARSE, HCS_TOK_STRINGIFY, HCS_TOK_ENCODE, HCS_TOK_DECODE,
    HCS_TOK_REGEX, HCS_TOK_MATCH, HCS_TOK_TEST, HCS_TOK_SEARCH,
    
    /* Keywords - System */
    HCS_TOK_RUN, HCS_TOK_EXEC, HCS_TOK_SHELL, HCS_TOK_EXIT, HCS_TOK_ENV, HCS_TOK_CLIPBOARD,
    HCS_TOK_NOTIFY, HCS_TOK_BEEP,
    
    /* Literals */
    HCS_TOK_NUMBER, HCS_TOK_STRING, HCS_TOK_IDENTIFIER,
    
    /* Operators */
    HCS_TOK_PLUS, HCS_TOK_MINUS, HCS_TOK_MULTIPLY, HCS_TOK_DIVIDE, HCS_TOK_MODULO, HCS_TOK_POWER,
    HCS_TOK_EQUAL, HCS_TOK_NOT_EQUAL, HCS_TOK_GREATER, HCS_TOK_LESS, HCS_TOK_GREATER_EQ, HCS_TOK_LESS_EQ,
    HCS_TOK_ASSIGN, HCS_TOK_PLUS_ASSIGN, HCS_TOK_MINUS_ASSIGN, HCS_TOK_MUL_ASSIGN, HCS_TOK_DIV_ASSIGN,
    HCS_TOK_INCREMENT, HCS_TOK_DECREMENT,
    
    /* Delimiters */
    HCS_TOK_LPAREN, HCS_TOK_RPAREN, HCS_TOK_LBRACE, HCS_TOK_RBRACE, HCS_TOK_LBRACKET, HCS_TOK_RBRACKET,
    HCS_TOK_COMMA, HCS_TOK_DOT, HCS_TOK_COLON, HCS_TOK_SEMICOLON, HCS_TOK_ARROW, HCS_TOK_QUESTION,
    HCS_TOK_NEWLINE,
    
    /* Special */
    HCS_TOK_EOF, HCS_TOK_UNKNOWN
} HcsTokenType;

/* AST Node types */
typedef enum {
    HCS_AST_PROGRAM,
    HCS_AST_CREATE_WINDOW, HCS_AST_CREATE_CONTROL, HCS_AST_CREATE_TIMER, HCS_AST_CREATE_MENU,
    HCS_AST_CREATE_DIALOG,
    HCS_AST_EVENT_HANDLER,
    HCS_AST_ALERT, HCS_AST_CONFIRM, HCS_AST_PROMPT, HCS_AST_PRINT,
    HCS_AST_SET_PROPERTY, HCS_AST_GET_PROPERTY,
    HCS_AST_LIST_OP, HCS_AST_WINDOW_ACTION, HCS_AST_CONTROL_ACTION, HCS_AST_TIMER_ACTION,
    HCS_AST_MEDIA_ACTION, HCS_AST_DIALOG_ACTION,
    HCS_AST_VAR_DECL, HCS_AST_ASSIGNMENT, HCS_AST_ARRAY_ASSIGNMENT,
    HCS_AST_FUNC_DECL, HCS_AST_FUNC_CALL, HCS_AST_RETURN, HCS_AST_BREAK, HCS_AST_CONTINUE,
    HCS_AST_IF, HCS_AST_WHILE, HCS_AST_FOR, HCS_AST_FOR_EACH, HCS_AST_SWITCH, HCS_AST_TRY_CATCH,
    HCS_AST_FILE_OP, HCS_AST_HTTP_REQUEST, HCS_AST_WAIT, HCS_AST_TIMEOUT, HCS_AST_INTERVAL,
    HCS_AST_CLIPBOARD, HCS_AST_NOTIFY, HCS_AST_SHELL, HCS_AST_IMPORT,
    /* Expressions */
    HCS_AST_NUMBER, HCS_AST_STRING, HCS_AST_BOOL, HCS_AST_NULL,
    HCS_AST_ARRAY, HCS_AST_OBJECT, HCS_AST_VAR_REF,
    HCS_AST_ARRAY_ACCESS, HCS_AST_PROPERTY_ACCESS,
    HCS_AST_BINARY_EXPR, HCS_AST_UNARY_EXPR, HCS_AST_TERNARY_EXPR,
    HCS_AST_FUNC_CALL_EXPR, HCS_AST_METHOD_CALL, HCS_AST_LAMBDA, HCS_AST_NEW_EXPR
} HcsAstNodeType;

/* Value types */
typedef enum {
    HCS_VAL_NULL,
    HCS_VAL_NUMBER,
    HCS_VAL_STRING,
    HCS_VAL_BOOL,
    HCS_VAL_ARRAY,
    HCS_VAL_OBJECT,
    HCS_VAL_FUNCTION
} HcsValueType;

#endif /* HALCYON_H */
